n = input()
c = int(input())
v = int(input())
m = int(input())
print('Чек'.center(35, '='))
print(f'Товар:{n.rjust(29, " ")}')
print('Цена:' + f'{v}кг * {c}руб/кг'.rjust(30, " "))
print('Итого:' + f'{c * v}руб'.rjust(29, " "))
print('Внесено:' + f'{m}руб'.rjust(27, " "))
print('Сдача:' + f'{m - c * v}руб'.rjust(29, " "))
print('=' * 35)
